/** Default engine settings — apps override via createEngine({ settings }). */
export const DEFAULT_SETTINGS = {
  browser_human_behavior: true,
  human_type_delay_min: 45,
  human_type_delay_max: 130,
  human_long_text_threshold: 80,
  smart_fill_passes: 3,
  ai_fill_enabled: false,
  agent_enabled: true,
  agent_max_steps: 24,
  agent_ai: false,
  objective_mode: true,
  cloudflare_wait_enabled: true,
  cloudflare_wait_timeout_sec: 120,
  site_mappings_path: "",
  site_learnings_path: "",
  site_accounts_path: "",
  auto_signup_enabled: true,
  account_email_base: "",
  listing_mode: true,
  browser_sessions_dir: "",
  email_verify_enabled: true,
  email_verify_timeout_ms: 25000,
  email_imap_host: "",
  email_imap_user: "",
  email_imap_pass: "",
  vision_fallback_enabled: false,
  vision_include_screenshot: true,
  captcha_solver_enabled: false,
  captcha_solver_url: "",
};
